#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NatureFormASPCore
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Page : PageBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<html>\n        <head>\n            <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\n            <title> Игрушки из полимерной глины</title>\n            <!--link re" +
"l=\"stylesheet\" type=\"text/css\" href=\"~/CSS/styles.css\"-->\n\t\t\t<!--%: Styles.Rende" +
"r(\"~/bundles/stylesCSS\") %-->\n            <meta");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" content=\"Арт-объединение \'Природа Формы\' предлагает широкий спектр скульптурных " +
"услуг \'своими руками\' \"");

WriteLiteral(" />\n            <meta");

WriteLiteral(" name=\"Keywords\"");

WriteLiteral(@" content=""глиняные фигурки, своими руками, купить, куклы, для начинающих, скульптура, игрушки из полимерной глины, полимерная глина, мастер-класс, фото, на заказ, полімерна глина,купити, в домашніх умовах, ціна, майстер-клас, вироби, недорого, купити через інтернет, купить в киеве, купить украина, новогодние поделки""");

WriteLiteral(">\n        </head>\n        <body>\n            <div class = \"header\"> \n            " +
"    <div class = \"logo\">\n                    <img");

WriteLiteral(" src=\"Pictures/Logo.png\"");

WriteLiteral(" alt=\"Logo Icon\"");

WriteLiteral(">\n                </div>\n                <div class = \"menuBar\">\n                " +
"    <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\n                        <img");

WriteLiteral(" src=\"Pictures/MenuItems/MenuItem1.png\"");

WriteLiteral(" alt=\"MenuItem1\"");

WriteLiteral(">\n                        <img");

WriteLiteral(" src=\"Pictures/MenuItems/MenuItem2.png\"");

WriteLiteral(" alt=\"MenuItem2\"");

WriteLiteral("><img");

WriteLiteral(" src=\"Pictures/MenuItems/MenuItem3.png\"");

WriteLiteral(" alt=\"MenuItem3\"");

WriteLiteral(">\n                        <img");

WriteLiteral(" src=\"Pictures/MenuItems/MenuItem4.png\"");

WriteLiteral(" alt=\"MenuItem4\"");

WriteLiteral(">\n                        <img");

WriteLiteral(" src=\"Pictures/MenuItems/MenuItem5.png\"");

WriteLiteral(" alt=\"MenuItem5\"");

WriteLiteral(@">       
                    </div>

                    <div class =""menuClickableText"">
                        <form>
                             <button>Хто ми</button>
                             <button>Наші Роботи</button>
                             <button>Замовити</button>
                             <button>Майстер-класи</button> 
                             <button>Профіль</button>
                        </form>
                    </div>
                    
                </div>
                <div class = ""contactsBar"">
                    <label>098-87-87-354</label>
                    <label>063-60-70-170</label>
                    <label>095-89-09-315</label>
                </div>
                <div class = ""userLogo"">
                	<img");

WriteLiteral(" src=\"Pictures/userLogo.png\"");

WriteLiteral(" alt=\"User Logo Icon\"");

WriteLiteral(">\n                </div>\n            </div>\n            <div class = \"InternalSpa" +
"ce\">\n\t            <div class = \"content\">\n\t\t\t\t\t<!--\n\t                <h1 class=\"" +
"titleContent\">\n\t                    Арт-об’єднання «Природа Форми» - Ми змінимо " +
"ваше уявлення про реальність\n\t                </h1>\n\t                <img src=\"P" +
"ictures/firstPictureContent.png\" class= \"contentImage\"/>\n\t                <div c" +
"lass=\"textContent\">\n\t                    <p> Ми працюємо на ринку скульптурних п" +
"ослуг з початку 2012 року. Незважаючи на місце нашої локації, ми реалізуємо скул" +
"ьптурні проекти по всій країні.\n\t                 Всі скульптори «Природи форми»" +
" є талановитими майстрами та мають неабиякий досвід роботи, відзнаки переможців " +
"та дипломи учасників багатьох українських та міжнародних скульптурних конкурсів." +
" Незважаючи на це, кожного дня ми намагаємося навчатися та вдосконалювати майсте" +
"рність.\n\t                 Ми надаємо повний спектр послуг  - від розробки ідеї т" +
"а проектування пам’ятників до кінцевого виготовлення скульптур - втілення у мате" +
"ріалі.  Тобто реалізуємо скульптурні проекти під ключ. </p>\n\t                 <p" +
">Congratulations! I’m Prefect Robert Hilliard, and I’m delighted to welcome you " +
"to RAVENCLAW HOUSE. Our emblem is the eagle, which soars where others cannot cli" +
"mb; our house colours are blue and bronze, and our common room is found at the t" +
"op of Ravenclaw Tower, behind a door with an enchanted knocker. The arched windo" +
"ws set into the walls of our circular common room look down at the school ground" +
"s: the lake, the Forbidden Forest, the Quidditch pitch and the Herbology gardens" +
". No other house in the school has such stunning views.  </p>\n\t                 " +
"<p>he’s the best and most knowledgeable Charms master alive in the world today. " +
"His office door is always open to any Ravenclaw with a problem, \nand if you’re i" +
"n a real state he’ll get out these delicious little cupcakes he keeps in a tin i" +
"n his desk drawer and make them do a little dance for you. In fact, it’s worth p" +
"retending you’re in a real state just to see them jive. </p>\n\n\t                 " +
"<p>Ravenclaw house has an illustrious history. Most of the greatest wizarding in" +
"ventors and innovators were in our house, including Perpetua Fancourt, the inven" +
"tor of the lunascope, Laverne de Montmorency, a great pioneer of love potions, a" +
"nd Ignatia Wildsmith, the inventor of Floo powder. Famous Ravenclaw Ministers fo" +
"r Magic include Millicent Bagnold, who was in power on the night that Harry Pott" +
"er survived the Dark Lord’s curse, and defended the wizarding celebrations all o" +
"ver Britain with the words, ‘I assert our inalienable right to party\'. There was" +
" also Minister Lorcan McLaird, who was a quite brilliant wizard, but preferred t" +
"o communicate by puffing smoke out of the end of his wand. Well, I did say we pr" +
"oduce eccentrics. In fact, we are also the house that gave the wizarding world U" +
"ric the Oddball, who used a jellyfish for a hat. He’s the punch line of a lot of" +
" wizarding jokes. </p>\n\t                </div>\n\t                <img src=\"Pictur" +
"es/SecondPictureContent.png\" class= \"contentImage\"/>\n\t                <div class" +
"=\"textContent\">\n\t                    <p>Without wishing to boast, this is the ho" +
"use where the cleverest witches and wizards live. Our founder, Rowena Ravenclaw," +
" prized learning above all else – and so do we. Unlike the other houses, who all" +
" have concealed entrances to their common rooms, we don’t need one. The door to " +
"our common room lies at the top of a tall, winding staircase. It has no handle, " +
"but an enchanted bronze knocker in the shape of an eagle. When you rap on the do" +
"or, this knocker will ask you a question, and if you can answer it correctly, yo" +
"u are allowed in. This simple barrier has kept out everyone but Ravenclaws for n" +
"early a thousand years. </p>\n\n\t                <p>Some first-years are scared by" +
" having to answer the eagle’s questions, but don’t worry. Ravenclaws learn quick" +
"ly, and you’ll soon enjoy the challenges the door sets. It’s not unusual to find" +
" twenty people standing outside the common room door, all trying to work out the" +
" answer to the day’s question together. This is a great way to meet fellow Raven" +
"claws from other years, and to learn from them – although it is a bit annoying i" +
"f you’ve forgotten your Quidditch robes and need to get in and out in a hurry. I" +
"n fact, I’d advise you to triple-check your bag for everything you need before l" +
"eaving Ravenclaw Tower.\n </p>\n\t                 <p>Another cool thing about Rave" +
"nclaw is that our people are the most individual – some might even call them ecc" +
"entrics. But geniuses are often out of step with ordinary folk, and unlike some " +
"other houses we could mention, we think you’ve got the right to wear what you li" +
"ke, believe what you want, and say what you feel. We aren’t put off by people wh" +
"o march to a different tune; on the contrary, we value them! </p>\n\n\t            " +
"    <p>Speaking of eccentrics, you’ll like our Head of house, Professor Filius F" +
"litwick. People often underestimate him, because he’s really tiny (we think he’s" +
" part elf, but we’ve never been rude enough to ask) and he’s got a squeaky voice" +
", but \nAs for our relationship with the other three houses: well, you’ve probabl" +
"y heard about the Slytherins. They’re not all bad, but you’d do well to be on yo" +
"ur guard until you know them well. They’ve got a long house tradition of doing w" +
"hatever it takes to win – so watch out, especially in Quidditch matches and exam" +
"s. </p>\n\n\t                <p>The Gryffindors are OK. If I had a criticism, I’d s" +
"ay Gryffindors tend to be show-offs. They’re also much less tolerant than we are" +
" of people who are different; in fact, they’ve been known to make jokes about Ra" +
"venclaws who have developed an interest in levitation, or the possible magical u" +
"ses of troll bogies, or ovomancy, which (as you probably know) is a method of di" +
"vination using eggs. Gryffindors haven’t got our intellectual curiosity, whereas" +
" we’ve got no problem if you want to spend your days and nights cracking eggs in" +
" a corner of the common room and writing down your predictions according to the " +
"way the yolks fall. In fact, you’ll probably find a few people to help you. </p>" +
"\n\n\t                <p>As for the Hufflepuffs, well, nobody could say they’re not" +
" nice people. In fact, they’re some of the nicest people in the school. Let’s ju" +
"st say you needn’t worry too much about them when it comes to competition at exa" +
"m time. </p>\n\n\t                <p>I think that’s nearly everything. Oh yes, our " +
"house ghost is the Grey Lady. The rest of the school thinks she never speaks, bu" +
"t she’ll talk to Ravenclaws. She’s particularly useful if you’re lost, or you’ve" +
" mislaid something. </p>\n\n\t                <p>I’m sure you’ll have a good night." +
" Our dormitories are in turrets off the main tower; our four-poster beds are cov" +
"ered in sky blue silk eiderdowns and the sound of the wind whistling around the " +
"windows is very relaxing. </p>\n\n\t                <p>And once again: well done on" +
" becoming a member of the cleverest, quirkiest and most interesting house at Hog" +
"warts. </p>\n\t                </div>\n\t\t\t\t\t<img src=\"Pictures/GreyLogo.png\" alt=\"L" +
"ogo Icon\" class = \"greyLogo\"/-->  \n\t                    \n\t            </div>\n\t  " +
"          <div");

WriteLiteral(" class=\"contentNavigation\"");

WriteLiteral(@">
	            
	            </div>
	            <!--
	            <script type=""text/javascript"">
	            	window.onload = function(){
	            		var parent = document.querySelector('div.InternalSpace'),
	            			child = document.querySelector('div.contentNavigation');
	            			
	            			child.style.height = parent.clientHeight;
	            	}
	            </script>
	            -->
            </div>
            <div class = ""footer"">
                <div");

WriteLiteral(" class=\"footerMainContent\"");

WriteLiteral(">\n\t                <div class = \"footerLogo\">\n\t                    <img");

WriteLiteral(" src=\"Pictures/Logo.png\"");

WriteLiteral(" alt=\"Logo Icon\"");

WriteLiteral("  >\n\t                </div>\n                     <div");

WriteLiteral(" class=\"contactsLTD\"");

WriteLiteral(">\n                          <label>Ukraine, Kyiv, st. Yangela 5, </label>\n       " +
"                   <label>Nature Science LTD</label>\n                         <l" +
"abel>vitalyzhynov@gmail.com</label>\n                    </div>\n                 " +
"   <div");

WriteLiteral(" class=\"contactsFooter\"");

WriteLiteral(">\n                         <label>098-87-87-354</label>\n                         " +
"<label>098-87-87-354</label>\n                         <label>098-87-87-354</labe" +
"l>\n                     </div>\n                </div>\n                <div");

WriteLiteral(" class=\"LogoDecorRights\"");

WriteLiteral(">\n                 \t<img");

WriteLiteral(" src=\"Pictures/CopyRightsSymb.png\"");

WriteLiteral(" alt=\"Copy Rights Icon\"");

WriteLiteral(" >\n                </div>\n            </div>\n        </body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class PageBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
